### ISSUE TITLE
Ambiguous address in "Enable DNS over HTTPS" guides

### ISSUE THREAD

**Issue by dotnetCarpenter** [censurfridns/client-configs#10]
In both the [Edge](https://github.com/censurfridns/client-configs/blob/main/edge.md) and [Firefox](https://github.com/censurfridns/client-configs/blob/main/firefox.md) guide it says in the text to point to `anycast.censurfridns.dk` but the images show `https://anycast.uncensoreddns.org/dns-query`.

**Which address is correct?**

Below is the relevant screen shots from the guides.

![Edge screenshot showing https://anycast.uncensoreddns.org/dns-query](https://github.com/censurfridns/client-configs/blob/main/screenshots/edge_4.png?raw=true)
_Edge screenshot showing https://anycast.uncensoreddns.org/dns-query_

![Firefox screenshot showing https://anycast.uncensoreddns.org/dns-query](https://github.com/censurfridns/client-configs/raw/main/screenshots/ff_5.png?raw=true)
_Firefox screenshot showing https://anycast.uncensoreddns.org/dns-query_

**Comment by tykling** [comment]
Both are equally correct. Danish speakers might prefer the `censurfridns.dk` domain and english speakers might prefer the `uncensoreddns.org` domain. Both work equally well, both are in all the certificates and can be used interchangably.

**Comment by dotnetCarpenter** [comment]
Gotcha! Thanks

So the protocol and path part is also interchangeable? E.g. `https` or without and `/dns-query` or root path.

**Comment by fjerhammer** [comment]
Entering `anycast.censurfridns.dk` like mentioned in the guide doesn't work for me using Firefox 105.0.2 on Linux. It simply ignores the setting and falls back to using the system-wide DNS resolver, so I think the protocol and/or path is required.
It works when using `https://anycast.uncensoreddns.org/dns-query` or `https://anycast.censurfridns.dk/dns-query`.

I made a pull request to change the Firefox guide: https://github.com/censurfridns/client-configs/pull/12
The same change might be needed for Edge, however I don't have a Windows machine available for testing right now.

**Comment by tykling** [comment]
merged - thanks! :)
